# Generated by Django 5.1.1 on 2025-09-05 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Instructor', 'Instructor'), ('Student', 'Student')], max_length=50, verbose_name='Role')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Sex')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', max_length=20, verbose_name='Account Status')),
                ('fingerprint_template', models.BinaryField(blank=True, null=True, verbose_name='Fingerprint Template')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Registration')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=50)),
                ('course_section', models.CharField(editable=False, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('course_code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('time_in', models.TimeField(verbose_name='Time In')),
                ('time_out', models.TimeField(verbose_name='Time Out')),
                ('days', models.CharField(max_length=50, verbose_name='Day/s')),
                ('grace_period', models.PositiveIntegerField(verbose_name='Grace Period (minutes)')),
                ('student_count', models.PositiveIntegerField(verbose_name='Student Count')),
                ('remote_device', models.CharField(max_length=100, verbose_name='Remote Device (Serial or Name)')),
                ('room_assignment', models.CharField(max_length=100, verbose_name='Room Assignment')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'role': 'Instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='PTLT_App.account', verbose_name='Professor')),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time_in', models.TimeField(verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Time Out')),
                ('fingerprint_data', models.BinaryField(verbose_name='Fingerprint Data')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent'), ('Excused', 'Excused'), ('No time-out', 'No time-out')], max_length=15, verbose_name='Status')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_as_professor', to='PTLT_App.account')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_as_student', to='PTLT_App.account')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTLT_App.classschedule', verbose_name='Class Schedule')),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section'),
        ),
    ]
