# Generated by Django 5.1.1 on 2025-10-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
