# Generated by Django 5.1.1 on 2025-07-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=50)),
                ('course_section', models.CharField(editable=False, max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='section',
        ),
        migrations.AddField(
            model_name='account',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section'),
        ),
        migrations.AddField(
            model_name='fingerprintregistration',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PTLT_App.coursesection', verbose_name='Course & Section'),
        ),
    ]
