# Generated by Django 5.1.1 on 2025-07-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0002_coursesection_remove_classschedule_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='PTLT_App.account', verbose_name='Professor'),
        ),
    ]
