# Generated by Django 5.1.1 on 2025-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0002_semester_alter_classschedule_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='Password'),
        ),
    ]
