# Generated by Django 5.1.1 on 2025-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0003_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuploadnotification',
            name='notification_type',
            field=models.CharField(default='upload', max_length=50),
        ),
    ]
