# Generated by Django 5.1.1 on 2025-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0003_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fingerprint_template',
            field=models.TextField(blank=True, null=True, verbose_name='Fingerprint Template'),
        ),
    ]
