# Generated by Django 5.1.1 on 2025-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0004_alter_account_fingerprint_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUploadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
